definitions:
  result.Result:
    properties:
      code:
        description: 返回状态码
        type: integer
      data:
        description: 返回数据
      message:
        description: 提示信息
        type: string
    type: object
info:
  contact: {}
  description: Admin后台管理系统
  title: Admin 管理系统
  version: "1.0"
paths:
  /api/backupMysql:
    post:
      consumes:
      - application/json
      description: 通过SSH在Linux执行mysqldump并保存到本地SQL目录
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "503":
          description: Service Unavailable
          schema:
            additionalProperties: true
            type: object
      summary: 数据库备份
      tags:
      - 数据库备份接口
  /api/failed:
    get:
      description: 失败测试接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 失败测试接口
      tags:
      - 测试相关接口
  /api/login:
    post:
      consumes:
      - application/json
      description: 根据用户名和密码登录
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "503":
          description: Service Unavailable
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - 用户登录接口--不生成token
  /api/logintoken:
    post:
      consumes:
      - application/json
      description: 根据用户名和密码登录
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "503":
          description: Service Unavailable
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - 用户登录接口--生成token
  /api/success:
    get:
      description: 成功测试接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 成功测试接口
      tags:
      - 测试相关接口
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
